{{ if .Values.letsencrypt.enabled }}
{{ if .Values.hosts }}

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: porta-tls
  namespace: kube-system
  labels:
    helm.sh/chart: {{ include "chartname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/stage: {{ .Values.stage }}
spec:
  # Name of a secret used to store the ACME account private key
  secretName: porta-tls
  commonName: 'porta.langetreedorpie.nl'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - 'porta.langetreedorpie.nl'

{{ end }}
{{ end }}
