lint Helm Charts:
  image:
    name: dtzar/helm-kubectl:3.0.0
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm lint service certs 

pages:
  image:
    name: dtzar/helm-kubectl:3.0.0
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - mkdir -p ./public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package service --destination ./public
    - helm repo index --url https://portadial.gitlab.io/integration/helm-charts/ ./public
  artifacts:
    paths:
      - public
  only:
    - master