lint Helm Charts:
  image:
    name: linkyard/docker-helm
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - helm lint pulr certs

pages:
  image:
    name: linkyard/docker-helm
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - helm init --client-only
    - mkdir -p ./public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package pulr --destination ./public
    - helm repo index --url https://pulr.gitlab.io/integration/helm-charts/ ./public
  artifacts:
    paths:
      - public
  only:
    - master