apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ include "namespace" . }}
  labels:
    helm.sh/chart: {{ include "chartname" . }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-config: "connectapi/data/config"
        vault.hashicorp.com/agent-inject-template-config: |
              {{`{{ with secret "connectapi/data/config" -}}
                  {{ range $k, $v := .Data.data }}
                    export {{ $k }}={{ $v }}
                  {{ end }}
              {{- end }}`}}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: server
          image: {{ include "image" . }}
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          args: ["/bin/sh", "-c", "source /vault/secrets/config && gunicorn -w 1 -k gevent -b 0.0.0.0:8000 manage:app"]
          livenessProbe:
            httpGet:
              path: {{ .Values.web.healthcheck }}
              port: {{ .Values.web.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.web.healthcheck }}
              port: {{ .Values.web.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          resources:
            requests:
              memory: {{ div .Values.web.memoryLimit 2 }}Mi
              cpu: {{ div .Values.web.cpuLimit 4 }}m
            limits:
              memory: {{ .Values.web.memoryLimit }}Mi
              cpu: {{ .Values.web.cpuLimit }}m
      imagePullSecrets:
        - name: regcred