app:
  repository: containers.pkg.github.com/portadial/connect
  version: 'v0.1.3'
  pullPolicy: IfNotPresent

web:
  replicas: 1
  port: 80
  healthcheck: /
  initializationCommand:
    - nginx
    - -g
    - 'daemon off;'
  memoryLimit: 512
  cpuLimit: 500

hosts:
  - 'connect.portadial.nl'