apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: s.gies21@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # Enable the HTTP-01
    http01: {}
    # Enable the DNS-01 challenge provider

    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: s.gies21@gmail.com
          apiKeySecretRef:
            name: cloudflare
            key: api